### ISSUE TITLE
adddate and subdate not support on opendistro 1.11 version

### ISSUE THREAD

**Issue by bigfishman** [opendistro-for-elasticsearch/sql#1000]
opendistro  sql version 1.11  elasticsearch  7.9.3

```
PUT test1
{
  "mappings" : {
      "properties" : {
        "order_time" : {
          "type" : "date",
         "format": "yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
        },
        "role_id" : {
          "type" : "keyword"
        },
        "refund_status":{
          "type":"integer"
        },
        "order_type":{
          "type":"keyword"
        }
      }
    }
}

POST test1/_doc
{
  "role_id":"6650703e451411ea8b5f0a58ac1d82b6",
  "order_time":"2021-01-22 03:33:07",
  "refund_status":1,
  "order_type":"fish"
}


POST /_opendistro/_sql?format=jdbc
{
"query":
  """
SELECT adddate(date('2021-0-22'), INTERVAL 1 hour) FROM test1 LIMIT 1
  """
}

POST /_opendistro/_sql?format=jdbc
{
  "query":
  """
  SELECT subdate(date('2008-01-02'), INTERVAL 31 day) FROM test1 LIMIT 1
  """
}

use adddate and subdate  show error:

{
  "error": {
    "reason": "Invalid SQL query",
    "details": "",
    "type": "NullPointerException"
  },
  "status": 400
}

```
log in elasticsearch

```
[2021-01-22T20:50:42,726][INFO ][c.a.o.s.l.p.RestSqlAction] [Es-0325-007] [cd6f7e31-bd04-41d9-bfd9-dfd829f25d2e] Incoming request /_opendistro/_sql?pretty=true: ( SELECT subdate(date('string_literal'), INTERVAL number DAY) FROM table LIMIT number )
[2021-01-22T20:50:42,737][ERROR][c.a.o.s.l.p.RestSqlAction] [Es-0325-007] cd6f7e31-bd04-41d9-bfd9-dfd829f25d2e Client side error during query execution
java.lang.NullPointerException: null
        at com.amazon.opendistroforelasticsearch.sql.legacy.domain.KVValue.toString(KVValue.java:36) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.utils.Util.joiner(Util.java:65) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.domain.MethodField.toString(MethodField.java:68) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.domain.MethodField.<init>(MethodField.java:43) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.FieldMaker.makeMethodField(FieldMaker.java:416) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.FieldMaker.makeFieldImpl(FieldMaker.java:105) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.FieldMaker.makeField(FieldMaker.java:62) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.SqlParser.findSelect(SqlParser.java:138) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.SqlParser.parseSelect(SqlParser.java:95) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.parser.SqlParser.parseSelect(SqlParser.java:82) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.query.ESActionFactory.create(ESActionFactory.java:127) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.plugin.SearchDao.explain(SearchDao.java:61) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.plugin.RestSqlAction.explainRequest(RestSqlAction.java:205) [legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.plugin.RestSqlAction.prepareRequest(RestSqlAction.java:167) [legacy-1.8.0.0.jar:?]
        at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:94) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:236) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:318) [elasticsearch-7.9.3.jar:7.9.3]
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176) [elasticsearch-7.9.3.jar:7.9.3]


```

**Comment by penghuo** [comment]
Thanks for the detail information.

**Comment by penghuo** [comment]
We are working on the release of [new SQL engine](https://github.com/opendistro-for-elasticsearch/sql#experimental) now. You could enable it using the [plugin setting] https://github.com/opendistro-for-elasticsearch/sql/blob/develop/docs/user/admin/settings.rst#opendistro-sql-engine-new-enabled

I am testing the query on ODFE 1.12.0.0, it works as expected.
```
PUT /_opendistro/_sql/settings
{
  "persistent" : {
    "opendistro.sql.engine.new.enabled" : "true"
  }
}

POST /_opendistro/_sql?format=jdbc
{
"query":
  """
SELECT adddate(date('2021-01-22'), INTERVAL 1 hour) FROM test1 LIMIT 1
  """
}

{
  "schema": [
    {
      "name": """adddate(date('2021-01-22'), INTERVAL 1 hour)""",
      "type": "datetime"
    }
  ],
  "datarows": [
    [
      "2021-01-22 01:00:00"
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```

**Comment by bigfishman** [comment]
Actually, I did it like this in 1.11 and elasticsearch 7.9.3   it  still doesn;t work

```
PUT /_opendistro/_sql/settings
{
  "persistent" : {
    "opendistro.sql.engine.new.enabled" : "true"
  }
}
```

**Comment by penghuo** [comment]
Have you try it on ODFE 1.12?

**Comment by dai-chen** [comment]
Closing as no response. Feel free to reopen if the suggestion above doesn't work. Thanks!
