### ISSUE TITLE
Using GROUP BY in JDBC with new sql engine failed 

### ISSUE THREAD

**Issue by boicehuang** [opendistro-for-elasticsearch/sql#1070]
Version 1.13

As mentioned in https://github.com/opendistro-for-elasticsearch/sql/issues/401,   query using GROUB BY is correct for NOT JSON formatting POST _opendistro/_sql/?sql= by using new SQL engine,  but still failed for JDBC query.

1. Open the new SQL engine: 
```
PUT /_opendistro/_sql/settings { "transient" : { "opendistro.sql.engine.new.enabled" : "true" } }
```

2. This query using GROUP BY with POST  succeed:
```
POST localhost:9200/_opendistro/_sql
{
    "query" : "SELECT title FROM movies GROUP BY title"
}
```

3. But it still failed for JDBC query 

java code
```
public static void queryTest() throws Exception {
        Class.forName("com.amazon.opendistroforelasticsearch.jdbc.Driver");
        String url = "jdbc:elasticsearch://localhost:9200";
        Properties properties = new Properties();
        String sql = "SELECT title FROM movies GROUP BY title";
        try (Connection connection = DriverManager.getConnection(url, properties);
             PreparedStatement statement = connection.prepareStatement(sql)) {
            ResultSet rs = statement.executeQuery();
            ResultSetMetaData metaData = rs.getMetaData();
            int numCols = metaData.getColumnCount();
            int numRows = 0;
            while (rs.next()) {
                System.out.print(++numRows + ":");
                for (int i = 1; i <= numCols; i++) {
                    System.out.print(metaData.getColumnLabel(i) + ":" + rs.getString(i) + "\t");
                }
                System.out.println();
            }
        }
    }
```
response:  
```
Exception in thread "main" Internal Server Error. Reason: There was internal problem at backend. Type: IllegalStateException. Details: invalid value operation on MISSING_VALUE
        at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:80)
        at com.amazon.opendistroforelasticsearch.jdbc.PreparedStatementImpl.executeQueryX(PreparedStatementImpl.java:87)
        at com.amazon.opendistroforelasticsearch.jdbc.PreparedStatementImpl.executeQuery(PreparedStatementImpl.java:78)
        at Main.queryTest(Main.java:41)
        at Main.main(Main.java:28)
```
error stack in es logs:
```
[2021-03-09T11:08:31,113][INFO ][c.a.o.s.l.p.RestSqlAction] [TENCENT64.site] [c148699c-ac29-4d53-b6dd-b25887916966] Incoming request /_opendistro/_sql?format=jdbc: ( SELECT identifier FROM table GROUP BY identifier )
[2021-03-09T11:08:31,118][WARN ][c.a.o.s.l.e.f.PrettyFormatRestExecutor] [TENCENT64.site] Error happened in pretty formatter
java.lang.IllegalStateException: invalid value operation on MISSING_VALUE
        at com.amazon.opendistroforelasticsearch.sql.legacy.expression.model.ExprValue.value(ExprValue.java:23) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.BindingTupleResultSet.lambda$buildDataRows$1(BindingTupleResultSet.java:59) ~[legacy-1.8.0.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.BindingTupleResultSet.buildDataRows(BindingTupleResultSet.java:66) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.BindingTupleResultSet.<init>(BindingTupleResultSet.java:38) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.Protocol.loadResultSet(Protocol.java:99) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.Protocol.<init>(Protocol.java:74) ~[legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:80) [legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:53) [legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.AsyncRestExecutor.doExecuteWithTimeMeasured(AsyncRestExecutor.java:161) [legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:121) [legacy-1.8.0.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.legacy.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) [legacy-1.8.0.0.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by penghuo** [comment]
Could you share the sample data and mapping for furthuer debugging?
In the error stack, I saw it call the function defined in the legacy engine.

**Comment by boicehuang** [comment]
@penghuo  I used data from https://aws.amazon.com/cn/blogs/china/build-run-sql-plugin-open-distro-elasticsearch-oss/

mapping:
```
{"aliases":{},"mappings":{"_source":{"enabled":false},"properties":{"actors":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"directors":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"genres":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"id":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"title":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}}
```


data:
```
curl -XPOST localhost:9200/movies/_doc/_bulk -H "Content-type: application/json" -d '{"index" : { } }
{"title": "Star Trek Into Darkness", "directors": ["J.J.Abrams"], "genres": ["Action", "Adventure", "Sci-Fi"], "actors": ["Chris Pine", "Zachary Quinto", "Zoe Saldana"], "id": "tt1408101"}
{"index" : { } }
{"title": "Star Wars", "directors": ["George Lucas"], "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"], "actors": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"], "id": "tt0076759"}
{"index" : { } }
{"title": "Rush", "directors": ["Ron Howard"], "genres": ["Action", "Biography", "Drama", "Sport"], "actors": ["Daniel Br\u00fchl", "Chris Hemsworth", "Olivia Wilde"], "id": "tt1979320"}
{"index" : { } }
{"title": "Gravity", "directors": ["Alfonso Cuar\u00f3n"], "genres": ["Drama", "Sci-Fi", "Thriller"], "actors": ["Sandra Bullock", "George Clooney", "Ed Harris"], "id": "tt1454468"}
{"index" : { } }
{"title": "The Avengers", "directors": ["Joss Whedon"], "genres": ["Action", "Fantasy"], "actors": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"], "id": "tt0848228"}
{"index" : { } }
{"title": "The Dark Knight Rises", "directors": ["Christopher Nolan"], "genres": ["Action", "Crime", "Thriller"], "actors": ["Christian Bale", "Tom Hardy", "Anne Hathaway"], "id": "tt1345836"}
{"index" : { } }
{"directors": ["Quentin Tarantino"], "genres": ["Adventure", "Drama", "Western"], "title": "Django Unchained", "actors": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"], "id": "tt1853728"}
'
```

**Comment by dai-chen** [comment]
@boicehuang Thanks for the info! I can reproduce from my side. Investigating.

**Comment by dai-chen** [comment]
I figured out the root cause. The query was handled by legacy engine instead of our new engine because of `PreparedStatement`. The new engine doesn't it so the fallback occurred when `parameters` found in request payload. It works when you change it to `Statement` as follows. We will add the support in new engine in future:

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Properties;

public class Main {

  public static void main(String[] args) throws Exception {
    queryTest();
  }

  public static void queryTest() throws Exception {
    Class.forName("com.amazon.opendistroforelasticsearch.jdbc.Driver");
    String url = "jdbc:elasticsearch://localhost:9200";
    Properties properties = new Properties();
    String sql = "SELECT title FROM movies GROUP BY title";
    try (Connection connection = DriverManager.getConnection(url, properties);
         //PreparedStatement statement = connection.prepareStatement(sql)) {
         Statement statement = connection.createStatement()) {
      ResultSet rs = statement.executeQuery(sql);
      ResultSetMetaData metaData = rs.getMetaData();
      int numCols = metaData.getColumnCount();
      int numRows = 0;
      while (rs.next()) {
        System.out.print(++numRows + ":");
        for (int i = 1; i <= numCols; i++) {
          System.out.print(metaData.getColumnLabel(i) + ":" + rs.getString(i) + "\t");
        }
        System.out.println();
      }
    }
  }
}
```

Data:

```
PUT movies/_bulk
{"index" : { } }
{"title": "Star Trek Into Darkness", "directors": ["J.J.Abrams"], "genres": ["Action", "Adventure", "Sci-Fi"], "actors": ["Chris Pine", "Zachary Quinto", "Zoe Saldana"], "id": "tt1408101"}
{"index" : { } }
{"title": "Star Wars", "directors": ["George Lucas"], "genres": ["Action", "Adventure", "Fantasy", "Sci-Fi"], "actors": ["Mark Hamill", "Harrison Ford", "Carrie Fisher"], "id": "tt0076759"}
{"index" : { } }
{"title": "Rush", "directors": ["Ron Howard"], "genres": ["Action", "Biography", "Drama", "Sport"], "actors": ["Daniel Br\u00fchl", "Chris Hemsworth", "Olivia Wilde"], "id": "tt1979320"}
{"index" : { } }
{"title": "Gravity", "directors": ["Alfonso Cuar\u00f3n"], "genres": ["Drama", "Sci-Fi", "Thriller"], "actors": ["Sandra Bullock", "George Clooney", "Ed Harris"], "id": "tt1454468"}
{"index" : { } }
{"title": "The Avengers", "directors": ["Joss Whedon"], "genres": ["Action", "Fantasy"], "actors": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"], "id": "tt0848228"}
{"index" : { } }
{"title": "The Dark Knight Rises", "directors": ["Christopher Nolan"], "genres": ["Action", "Crime", "Thriller"], "actors": ["Christian Bale", "Tom Hardy", "Anne Hathaway"], "id": "tt1345836"}
{"index" : { } }
{"directors": ["Quentin Tarantino"], "genres": ["Adventure", "Drama", "Western"], "title": "Django Unchained", "actors": ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio"], "id": "tt1853728"}

POST _opendistro/_sql
{
  "query": """
    SELECT title FROM movies GROUP BY title
  """
}
```

**Comment by boicehuang** [comment]
Good!

**Comment by dai-chen** [comment]
> Good!

The prepared statement support is already added in PR above. Thanks!
