### ISSUE TITLE
SQL did not support Long type

### ISSUE THREAD

**Issue by chyun** [opendistro-for-elasticsearch/sql#1080]
I change a unit test in AstBuilderTest.can_build_from_subquery.
`@Test
  public void can_build_from_subquery() {
    assertEquals(
        project(
            filter(
                relationSubquery(
                    project(
                        relation("test"),
                        alias("firstname", qualifiedName("firstname"), "firstName"),
                        alias("lastname", qualifiedName("lastname"), "lastName")
                    ),
                    "a"
                ),
                function(">", qualifiedName("age"), longLiteral(1616743864352L))
            ),
            alias("a.firstName", qualifiedName("a", "firstName")),
            alias("lastName", qualifiedName("lastName"))),
        buildAST(
            "SELECT a.firstName, lastName FROM ("
                + "SELECT firstname AS firstName, lastname AS lastName FROM test"
                + ") AS a where age > 1616743864352"
        )
    );
  }`

I simply change "age > 2" to "age > 1616743864352", and I got the following error.

`
java.lang.NumberFormatException: For input string: "1616743864352"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstExpressionBuilder.visitSignedDecimal(AstExpressionBuilder.java:258)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstExpressionBuilder.visitSignedDecimal(AstExpressionBuilder.java:95)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$SignedDecimalContext.accept(OpenDistroSQLParser.java:2463)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitConstantExpressionAtom(OpenDistroSQLParserBaseVisitor.java:440)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$ConstantExpressionAtomContext.accept(OpenDistroSQLParser.java:3876)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitExpressionAtomPredicate(OpenDistroSQLParserBaseVisitor.java:405)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$ExpressionAtomPredicateContext.accept(OpenDistroSQLParser.java:3627)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstExpressionBuilder.visitBinaryComparisonPredicate(AstExpressionBuilder.java:309)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstExpressionBuilder.visitBinaryComparisonPredicate(AstExpressionBuilder.java:95)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$BinaryComparisonPredicateContext.accept(OpenDistroSQLParser.java:3654)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitPredicateExpression(OpenDistroSQLParserBaseVisitor.java:398)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$PredicateExpressionContext.accept(OpenDistroSQLParser.java:3391)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitAstExpression(AstBuilder.java:203)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitWhereClause(AstBuilder.java:188)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitWhereClause(AstBuilder.java:58)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$WhereClauseContext.accept(OpenDistroSQLParser.java:1606)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitFromClause(AstBuilder.java:153)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitFromClause(AstBuilder.java:58)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$FromClauseContext.accept(OpenDistroSQLParser.java:1364)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:120)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilder.visitQuerySpecification(AstBuilder.java:58)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$QuerySpecificationContext.accept(OpenDistroSQLParser.java:912)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitSimpleSelect(OpenDistroSQLParserBaseVisitor.java:41)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$SimpleSelectContext.accept(OpenDistroSQLParser.java:437)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitDmlStatement(OpenDistroSQLParserBaseVisitor.java:34)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$DmlStatementContext.accept(OpenDistroSQLParser.java:385)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitSqlStatement(OpenDistroSQLParserBaseVisitor.java:27)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$SqlStatementContext.accept(OpenDistroSQLParser.java:325)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParserBaseVisitor.visitRoot(OpenDistroSQLParserBaseVisitor.java:20)
	at com.amazon.opendistroforelasticsearch.sql.sql.antlr.parser.OpenDistroSQLParser$RootContext.accept(OpenDistroSQLParser.java:257)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilderTest.buildAST(AstBuilderTest.java:683)
	at com.amazon.opendistroforelasticsearch.sql.sql.parser.AstBuilderTest.can_build_from_subquery(AstBuilderTest.java:518)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)`

And I located the code in class AstExpressionBuilder.
`@Override
  public UnresolvedExpression visitSignedDecimal(SignedDecimalContext ctx) {
    return AstDSL.intLiteral(Integer.valueOf(ctx.getText()));
  }`

Why use Integer.value instead of Long.value?

**Comment by dai-chen** [comment]
Thanks for reporting the issue! Investigating

**Comment by dai-chen** [comment]
Reproducing the issue:

```
POST _opendistro/_sql
{
  "query": """
    SELECT 1616743864352
  """
}
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "For input string: \"1616743864352\"",
    "type": "NumberFormatException"
  },
  "status": 400
}
```

**Comment by chyun** [comment]
@dai-chen the merge is still not accepted?

**Comment by dai-chen** [comment]
> @dai-chen the merge is still not accepted?

Need one more approval. @penghuo could you take a look? https://github.com/opendistro-for-elasticsearch/sql/pull/1083

Btw, we're migrating to the new repo: https://github.com/opensearch-project/sql. I will resend this PR and patch this changes.

**Comment by dai-chen** [comment]
@chyun Sorry for the delay! My PR for long literal support is already merged. Will patch it in OpenSearch later. Thanks!
