### ISSUE TITLE
Connection issue quering ES using opendistro driver

### ISSUE THREAD

**Issue by bernony** [opendistro-for-elasticsearch/sql#1132]
Hi all,
Thank you for this great tool you are striving to improve day after day for better experience.

Well, we started using the 1.6.0.0 opendistro driver. Few times ago, we upgraded the open distro plugin to 1.12.

We perform parallel queries against opendistro ES.

Currently, each time we perform the set of queries, at first time some/all of the queries systematically fail and  we get the following error:

`java.lang.IllegalStateException: Connection not obtained from this manager
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.util.Asserts.check(Asserts.java:34)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.conn.BasicHttpClientConnectionManager.releaseConnection(BasicHttpClientConnectionManager.java:260)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.execchain.ConnectionHolder.abortConnection(ConnectionHolder.java:135)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:351)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at com.amazonaws.opendistro.elasticsearch.sql.jdbc.shadow.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)`

Actually, this is thrown by the driver.

I would very appreciate any idea from anybody helping getting through this.

thanks in advance;

Regards

Bernony

**Comment by bernony** [comment]
Hi all,
No body has any idea?

Thanks in advance

Bernony
