### ISSUE TITLE
"_explain" for SQL query that contains union is not valid json

### ISSUE THREAD

**Issue by galkk** [opendistro-for-elasticsearch/sql#114]
Currently explain request for union query returns invalid json.

![example](https://user-images.githubusercontent.com/1936087/61157172-36a9bd00-a4aa-11e9-88f2-b64092352337.png)

**Comment by dai-chen** [comment]
We added JSON pretty formatter in https://github.com/opendistro-for-elasticsearch/sql/issues/166 which throws exception in this case.

```
[2019-10-31T15:39:23,593][WARN ][r.suppressed             ] [186590df9563.ant.amazon.com] path: /_opendistro/_sql/_explain, params: {pretty=}
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'performing': was expecting ('true', 'false' or 'null')
 at [Source: java.io.StringReader@5afbfe28; line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2839) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1903) ~[jackson-core-2.8.11.jar:2.8.11]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.11.jar:2.8.11]
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:52) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:415) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
	at org.elasticsearch.common.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:988) ~[elasticsearch-x-content-7.3.1.jar:7.3.1]
	at com.amazon.opendistroforelasticsearch.sql.utils.JsonPrettyFormatter.format(JsonPrettyFormatter.java:45) ~[?:?]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.executeSqlRequest(RestSqlAction.java:156) ~[?:?]
```
