### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by WindedMan** [opendistro-for-elasticsearch/sql#1156]
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.3
  OS Info               : Mac OS X 10.16 (x86_64)
  JDK Version           : 13 (OpenJDK)
  JAVA_HOME             : /Users/zxh/JDK13/jdk-13.jdk/Contents/Home
  Random Testing Seed   : AB0108D950116D8C
  In FIPS 140 mode      : false
=======================================

> Task :test

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testMultipleCustomFormats FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats(DateFieldFormatterTest.java:615)

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testNamedAndCustomFormats FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats(DateFieldFormatterTest.java:630)

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testCustomFormat FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat(DateFieldFormatterTest.java:589)

Suite: Test class com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest
  1> [2022-01-02T17:03:32,630][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 1581724085 as date_optional_time
  1> [2022-01-02T17:03:32,667][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  1> [2022-01-02T17:03:32,691][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 2015-01-01 as epoch_millis
  1> [2022-01-02T17:03:32,693][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 2015-01-01T12:10:30Z as epoch_millis
  1> [2022-01-02T17:03:32,694][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 1420070400001 as strict_date_optional_time
  1> [2022-01-02T17:03:32,718][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2022-01-02T17:03:32,718][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as yyMMddHHmmssZ
  1> [2022-01-02T17:03:32,719][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats(DateFieldFormatterTest.java:615)
  1> [2022-01-02T17:03:32,729][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2022-01-02T17:03:32,729][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as hour_minute_second
  1> [2022-01-02T17:03:32,730][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats(DateFieldFormatterTest.java:630)
  1> [2022-01-02T17:03:32,731][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2022-01-02T17:03:32,731][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:698)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:689)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat(DateFieldFormatterTest.java:589)
  1> [2022-01-02T17:03:32,737][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 1993-01-19 as epoch_millis
  1> [2022-01-02T17:03:32,745][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 727401600000 as date_optional_time
WARNING: Illegal reflective access by org.mockito.internal.creation.jmock.ClassImposterizer$3 (file:/Users/zxh/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to constructor java.time.Clock()

1609 tests completed, 3 failed, 39 skipped

Tests with failures:
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/zxh/Tbds/rxhzeng/sql/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 17s
27 actionable tasks: 1 executed, 26 up-to-date

**Comment by WindedMan** [comment]
how to solve this ?plz

**Comment by penghuo** [comment]
Are you trying to build plugin only? If so, you could use `./gradlew plugin:build` which will build plugin without run test.
Which branch you run test against? 
Have you considered use OpenSearch? OpenDistro-SQL will be on deprecation path. Instead, you could try https://github.com/opensearch-project/sql
