### ISSUE TITLE
Add support for subqueries

### ISSUE THREAD

**Issue by jordanw-bq** [opendistro-for-elasticsearch/sql#230]
Using Docker image `amazon/opendistro-for-elasticsearch:1.1.0`
**Dataset:** Flights sample data (loaded through Kibana)
**SQL Plugin version:** 1.1.0.1

**Example Query:**
SELECT t0.TEMP FROM (SELECT SUM(dayOfWeek) as TEMP FROM kibana_sample_data_flights) t0

**Result:**
```
Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "Different mappings are not allowed for the same field[config]: found [{type:text,fields:{keyword:{type:keyword,ignore_above:256}}}] and [{dynamic:true,properties:{buildNum:{type:keyword}}}] ",
    "type": "VerificationException"
  },
  "status": 400
}
```

**Note:**
This is a known limitation of Elasticsearch, but Tableau by default will be generating subqueries for a number of its queries. However, support for subqueries is something that can be customized using a Tableau Datasource Customization (TDC) file, though the extent of these customizations cannot be tested until the major Tableau blockers (#212, #213, #215) are resolved. 

**Expectation:**
Subquery support

**Comment by dai-chen** [comment]
We don't have support for this kind of subquery. And this seems broke term field rewriter too. May need major changes to add the support.

**Comment by jordanw-bq** [comment]
We've re-tested subqueries with the new changes (#278), but we are still finding errors. Even a simple case (adapted from the tests added as part of the aforementioned PR) does not seem to be working as expected.

Query: `SELECT t.TEMP as count FROM (SELECT COUNT(*) as TEMP FROM kibana_sample_data_flights) t`
Server logs:
```
[2019-12-12T01:16:05,452][INFO ][c.a.o.s.p.RestSqlAction  ] [odfe-node1] [b2007666-6ed1-4c7b-a6e8-2ce83325993a] Incoming request /_opendistro/_sql?format=jdbc: SELECT t.TEMP as count FROM (SELECT COUNT(*) as TEMP FROM kibana_sample_data_flights) t
[2019-12-12T01:16:05,457][ERROR][c.a.o.s.p.RestSqlAction  ] [odfe-node1] b2007666-6ed1-4c7b-a6e8-2ce83325993a Client side error during query execution
com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.VerificationException: Different mappings are not allowed for the same field[audit_rest_request_headers]: found [{properties:{content-length:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},password:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Accept:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Connection:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},User-Agent:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Host:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Postman-Token:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Content-Length:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},cache-control:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},user:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},accept-encoding:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Content-Type:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}}}}] and [{properties:{Connection:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},User-Agent:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},content-length:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Host:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Accept:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}},Content-Length:{type:text,fields:{keyword:{type:keyword,ignore_above:256}}}}}]
        at com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.TermFieldRewriter.verifySingleFieldMapping(TermFieldRewriter.java:298) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.TermFieldRewriter.lambda$checkMappingCompatibility$2(TermFieldRewriter.java:268) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
        at com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.TermFieldRewriter.checkMappingCompatibility(TermFieldRewriter.java:268) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.TermFieldRewriter.visit(TermFieldRewriter.java:84) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:255) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.dialect.mysql.ast.statement.MySqlSelectQueryBlock.accept0(MySqlSelectQueryBlock.java:246) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.statement.SQLSelect.accept0(SQLSelect.java:85) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.expr.SQLQueryExpr.accept0(SQLQueryExpr.java:55) ~[druid-1.0.15.jar:1.0.15]
        at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40) ~[druid-1.0.15.jar:1.0.15]
        at com.amazon.opendistroforelasticsearch.sql.query.ESActionFactory.create(ESActionFactory.java:104) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.amazon.opendistroforelasticsearch.sql.plugin.SearchDao.explain(SearchDao.java:59) ~[opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.explainRequest(RestSqlAction.java:143) [opendistro_sql-1.1.0.2.jar:1.1.0.2]
        at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.prepareRequest(RestSqlAction.java:113) [opendistro_sql-1.1.0.2.jar:1.1.0.2]
```

This error gets thrown both through the JDBC driver and when directly querying the SQL plugin through Postman (application for interacting with REST endpoints).

**Comment by penghuo** [comment]
I test with kibana_sample_data_flights, it return the correct result.
Could you confrim that the kibana_sample_data_flights index has correct mapping?

### SQL
```
POST _opendistro/_sql/?
{
  "query":"""
  SELECT t.TEMP as count FROM (SELECT COUNT(*) as TEMP FROM kibana_sample_data_flights) t
  """
}
```

### Result
```
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "count" : {
      "value" : 13059
    }
  }
}
```
