### ISSUE TITLE
can this support Elastic elasticsearch 6.3.1?

### ISSUE THREAD

**Issue by ltylty** [opendistro-for-elasticsearch/sql#321]
I install this plugin as below
# bin/elasticsearch-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-sql/opendistro_sql-1.2.1.0.zip
-> Downloading https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-plugins/opendistro-sql/opendistro_sql-1.2.1.0.zip
[=================================================] 100%   
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [opendistro_sql] was built for Elasticsearch version 7.2.1 but version 6.3.1 is running
	at org.elasticsearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:421)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:596)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:717)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:641)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:225)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:210)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:79)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)

**Comment by abbashus** [comment]
You need to change the Elasticsearch version to 7.2.1. You can download it from here
https://www.elastic.co/downloads/past-releases/elasticsearch-oss-7-2-1.


As another workaround change the `elasticsearch.version` to 6.3.1 in  plugin-descriptor.properties .

**Comment by ltylty** [comment]
I have changed the elasticsearch.version to 6.3.1 and install the plugin.But not work very well.
Do you plan to support Elasticsearch 6.3.1 in future?

**Comment by abbashus** [comment]
We do not plan to support versions older than 6.5.4.

**Comment by dai-chen** [comment]
@ltylty Other workaround: https://github.com/opendistro-for-elasticsearch/sql/issues/323#issuecomment-566177707

**Comment by dai-chen** [comment]
@ltylty It seems 0.7 branch can work with ES 6.3.1. Please refer to https://github.com/opendistro-for-elasticsearch/sql/issues/323#issuecomment-566428190. Closing this issue.
