### ISSUE TITLE
JSON does not allow non-finite numbers

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#331]
An error "JSON does not allow non-finite numbers" thrown when using math function. This may be caused by float number with too many digits after decimal point. No error stack found in ES log.

```
POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT acos(FlightDelayMin) FROM kibana_sample_data_flights"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT asin(FlightDelayMin) FROM kibana_sample_data_flights"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT log(FlightDelayMin) FROM kibana_sample_data_flights"
}

POST _opendistro/_sql?format=jdbc
{
  "query": "SELECT (log(FlightDelayMin)/log(10)) FROM kibana_sample_data_flights"
}
```

**Comment by dai-chen** [comment]
The root cause is trig functions only accepts [-1, 1]. For other cases, the result is NaN which causes the exception above in org.json library.

```
[2020-04-24T17:11:55,160][ERROR][c.a.o.s.e.AsyncRestExecutor] [186590df9563.ant.amazon.com] Error
org.json.JSONException: JSON does not allow non-finite numbers.
    at org.json.JSONObject.testValidity(JSONObject.java:2214) ~[json-20180813.jar:?]
    at org.json.JSONArray.put(JSONArray.java:1050) ~[json-20180813.jar:?]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.dataEntry(Protocol.java:255) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.getDataRowsAsJson(Protocol.java:245) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.outputInJdbcFormat(Protocol.java:159) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.format(Protocol.java:135) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:92) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:53) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.doExecuteWithTimeMeasured(AsyncRestExecutor.java:162) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:121) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.6.1.jar:7.6.1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:830) [?:?]

```

**Comment by dai-chen** [comment]
We should add argument check in painless script generated (or ideally in semantic analyzer) and return `NULL` for invalid arguments. Reference: https://www.w3schools.com/sql/func_sqlserver_acos.asp

**Comment by dai-chen** [comment]
This issue has been taken care of during new query engine development.
