### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by EveyWu** [opendistro-for-elasticsearch/sql#396]
build-log

```
> Task :printGlobalBuildInfo UP-TO-DATE
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 6.2.2
  OS Info               : Mac OS X 10.15.2 (x86_64)
  Compiler JDK Version  : 13 (N/A 13.0.2 [OpenJDK 64-Bit Server VM 13.0.2+8])
  Compiler java.home    : /usr/local/opt/openjdk
  Runtime JDK Version   : 13 (N/A 13.0.2 [OpenJDK 64-Bit Server VM 13.0.2+8])
  Runtime java.home     : /usr/local/opt/openjdk
  Gradle JDK Version    : 13 (Oracle Corporation 13.0.2 [Java HotSpot(TM) 64-Bit Server VM 13.0.2+8])
  Gradle java.home      : /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
  Random Testing Seed   : FC098ADF4B58F307
  In FIPS 140 mode      : false
=======================================

> Task :test

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testMultipleCustomFormats FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats(DateFieldFormatterTest.java:615)

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testNamedAndCustomFormats FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats(DateFieldFormatterTest.java:630)

com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest > testCustomFormat FAILED
    org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat(DateFieldFormatterTest.java:589)


Suite: Test class com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest
  1> [2020-03-26T16:59:21,182][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 1581724085 as date_optional_time
  1> [2020-03-26T16:59:21,223][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  1> [2020-03-26T16:59:21,284][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2020-03-26T16:59:21,286][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as yyMMddHHmmssZ
  1> [2020-03-26T16:59:21,286][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats(DateFieldFormatterTest.java:615)
  1> [2020-03-26T16:59:21,302][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2020-03-26T16:59:21,302][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as hour_minute_second
  1> [2020-03-26T16:59:21,303][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats(DateFieldFormatterTest.java:630)
  1> [2020-03-26T16:59:21,304][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string Tue, Jan 19, '93 as EEE, MMM d, ''yy
  1> [2020-03-26T16:59:21,304][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date value; returning original value
  2> org.junit.ComparisonFailure: expected:<[1993-01-19 00:00:00.000]> but was:<[Tue, Jan 19, '93]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.executeFormattingAndCompare(DateFieldFormatterTest.java:679)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.verifyFormatting(DateFieldFormatterTest.java:670)
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat(DateFieldFormatterTest.java:589)
  1> [2020-03-26T16:59:21,307][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 1993-01-19 as epoch_millis
  1> [2020-03-26T16:59:21,309][WARN ][c.a.o.s.e.f.DateFieldFormatter] [Test workerest_thread_info] Could not parse date string 727401600000 as date_optional_time
WARNING: Illegal reflective access by org.mockito.internal.creation.jmock.ClassImposterizer$3 (file:/Users/yiwenwu/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securemock/1.2/98201d4ad5ac93f6b415ae9172d52b5e7cda490e/securemock-1.2.jar) to constructor java.time.Clock()

1576 tests completed, 3 failed, 39 skipped

Tests with failures:
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testMultipleCustomFormats
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testNamedAndCustomFormats
 - com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatterTest.testCustomFormat

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/yiwenwu/code/git/sql/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 20s
29 actionable tasks: 5 executed, 24 up-to-date
```

**Comment by penghuo** [comment]
Do u run against the latest master branch?
The build successfully on the Github Action. https://github.com/opendistro-for-elasticsearch/sql/runs/535249791?check_suite_focus=true

**Comment by anirudha** [comment]
closing this issue, let us know if you need any more help on this

**Comment by WindedMan** [comment]
I have the same error ,plz how to solve this ? I use opendistro-1.7 branch , gradle build error !
