### ISSUE TITLE
Group By Range SQL ERROR

### ISSUE THREAD

**Issue by EveyWu** [opendistro-for-elasticsearch/sql#403]
## Demo SQL of README.md
```
SELECT COUNT(age) FROM bank GROUP BY range(age, 20,25,30,35,40)
```

## ERROR
```
{
  "error" : {
    "reason" : "There was internal problem at backend",
    "details" : "java.lang.RuntimeException: unsupported aggregation type range",
    "type" : "RuntimeException"
  },
  "status" : 500
}
```

## ES ERROR LOG
```
java.lang.RuntimeException: java.lang.RuntimeException: unsupported aggregation type range
	at com.amazon.opendistroforelasticsearch.sql.query.planner.core.BindingTupleQueryPlanner.execute(BindingTupleQueryPlanner.java:55) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.adapter.QueryPlanRequestBuilder.execute(QueryPlanRequestBuilder.java:37) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.QueryActionElasticExecutor.executeQueryPlanQueryAction(QueryActionElasticExecutor.java:65) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.QueryActionElasticExecutor.executeAnyAction(QueryActionElasticExecutor.java:109) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:70) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:47) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.doExecuteWithTimeMeasured(AsyncRestExecutor.java:161) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:121) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) [opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.6.1.jar:7.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.RuntimeException: unsupported aggregation type range
	at com.amazon.opendistroforelasticsearch.sql.query.planner.physical.node.scroll.SearchAggregationResponseHelper.flatten(SearchAggregationResponseHelper.java:78) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.query.planner.physical.node.scroll.SearchAggregationResponseHelper.populateSearchAggregationResponse(SearchAggregationResponseHelper.java:40) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.query.planner.physical.node.scroll.PhysicalScroll.open(PhysicalScroll.java:69) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.query.planner.physical.PhysicalOperator.open(PhysicalOperator.java:44) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	at com.amazon.opendistroforelasticsearch.sql.query.planner.core.BindingTupleQueryPlanner.execute(BindingTupleQueryPlanner.java:53) ~[opendistro_sql-1.6.0.0.jar:1.6.0.0]
	... 12 more
```

**Comment by penghuo** [comment]
Thanks for reporting the issue.

We are working in progress to support such query in JDBC format. But now, only the JSON formatting is supported.
```
POST _opendistro/_sql/?format=json
{
  "query": """
    SELECT COUNT(age) 
    FROM bank 
    GROUP BY range(age, 20,25,30,35,40)
  """
}
```

**Comment by EveyWu** [comment]
Thank you so much， It works for me for the JSON formatting

**Comment by EveyWu** [comment]
![image](https://user-images.githubusercontent.com/59307607/78146563-e5d95a80-7464-11ea-86fd-2cc33119cbbe.png)
