### ISSUE TITLE
gradle build fails locally

### ISSUE THREAD

**Issue by zhongnansu** [opendistro-for-elasticsearch/sql#443]
### Description
- gradle build fails locally after checkout commit https://github.com/opendistro-for-elasticsearch/sql/commit/bf4810dc26cc1782ab433bc97d63a6a0b326da11
- `git checkout <previous commit_id>` doesn't have this issue
- github Action doesn't have this issue

#### branch
master

#### environment
```
 Gradle Version        : 6.2.1
  OS Info               : Mac OS X 10.14.6 (x86_64)
  JDK Version           : 13 (Oracle Corporation 13.0.2 [Java HotSpot(TM) 64-Bit Server VM 13.0.2+8])
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home
  Random Testing Seed   : 176218B3C65D7194
  In FIPS 140 mode      : false
```

#### report
![image](https://user-images.githubusercontent.com/32652829/80453016-55176280-88dc-11ea-8f86-07e395024a30.png)

All failures are related to unit test package `com.amazon.opendistroforelasticsearch.sql.unittest.planner` with same error log
```
2> java.lang.NullPointerException: SQL setting is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:247)
        at com.amazon.opendistroforelasticsearch.sql.esdomain.LocalClusterState.getSettingValue(LocalClusterState.java:153)
        at com.amazon.opendistroforelasticsearch.sql.query.DefaultQueryAction.checkAndSetScroll(DefaultQueryAction.java:111)
        at com.amazon.opendistroforelasticsearch.sql.query.DefaultQueryAction.explain(DefaultQueryAction.java:89)
        at com.amazon.opendistroforelasticsearch.sql.query.join.ESJoinQueryAction.fillTableInJoinRequestBuilder(ESJoinQueryAction.java:119)
        at com.amazon.opendistroforelasticsearch.sql.query.join.ESJoinQueryAction.fillBasicJoinRequestBuilder(ESJoinQueryAction.java:60)
        at com.amazon.opendistroforelasticsearch.sql.query.join.ESJoinQueryAction.explain(ESJoinQueryAction.java:48)
        at com.amazon.opendistroforelasticsearch.sql.unittest.planner.QueryPlannerTest.createRequestBuilder(QueryPlannerTest.java:183)
        at com.amazon.opendistroforelasticsearch.sql.unittest.planner.QueryPlannerTest.plan(QueryPlannerTest.java:170)
        at com.amazon.opendistroforelasticsearch.sql.unittest.planner.QueryPlannerTest.query(QueryPlannerTest.java:165)
        at com.amazon.opendistroforelasticsearch.sql.unittest.planner.QueryPlannerBatchTest.departmentLeftJoinEmployee(QueryPlannerBatchTest.java:218)
```

**Comment by zhongnansu** [comment]
### RCA
#### Tried some fix but failed
  - `gradle clean & gradle build`
  - kill hanging gradle/es process and rebuild
  - switch to another laptop and `gradle build` passes. But while running those tests individually such as `./gradlew test --tests "com.amazon.opendistroforelasticsearch.sql.unittest.planner.QueryPlannerExplainTest.explainInJsonWithDuplicateColumnsPushedDown"`, it fails again.

#### Debug Analysis
- https://github.com/opendistro-for-elasticsearch/sql/blob/bf4810dc26cc1782ab433bc97d63a6a0b326da11/src/main/java/com/amazon/opendistroforelasticsearch/sql/query/DefaultQueryAction.java#L111
- `LocalClusterState` is not initialized with `sqlSettings`, which lead to the line above throw NPE
- the above code change took place in exact commit https://github.com/opendistro-for-elasticsearch/sql/commit/bf4810dc26cc1782ab433bc97d63a6a0b326da11, that explains why `git checkout <previous commit>` doesn't fail.

#### Proposed Solution
- initialize mock `LocalClusterState.sqlSettings` in base test class for `QueryPlannerTest`

**Comment by abbashus** [comment]
You can use [this](https://github.com/opendistro-for-elasticsearch/sql/blob/master/src/test/java/com/amazon/opendistroforelasticsearch/sql/unittest/query/DefaultQueryActionTest.java#L258) for inspiration to mock `LocalClusterState `

**Comment by anirudha** [comment]
is this fixed? or whats pending here ?

**Comment by abbashus** [comment]
Yes, this is fixed.
