### ISSUE TITLE
Open Distro Not allowing persistent connection for elasticsearch-py connector.

### ISSUE THREAD

**Issue by gaurav1999** [opendistro-for-elasticsearch/sql#465]
Hi,

I am trying to test ```https://github.com/preset-io/elasticsearch-dbapi ``` , 
here, we have some known limitations for Open Distro which are preventing the integration of Open Distro with Apache-Superset BI application.

In order to hack and help remove those limitations, I first need to setup Open Distro and be able to connect with it using the python connector.

The default test given in this repo ```https://github.com/preset-io/elasticsearch-dbapi/tree/master/es/tests``` tries to connect with Open Distro using plain URL.

The connection object gets created, but later on the remote disconnects.

```
[2020-05-13T21:28:44,372][ERROR][c.a.o.s.s.h.n.OpenDistroSecuritySSLNettyHttpServerTransport] [5ec4f538c9d9] Exception during establishing a SSL connection: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f64617461312f5f64656c6574655f62795f717565727920485454502f312e310d0a486f73743a206c6f63616c686f73743a393230300d0a4163636570742d456e636f64696e673a206964656e746974790d0a436f6e74656e742d4c656e6774683a2032360d0a636f6e6e656374696f6e3a206b6565702d616c6976650d0a636f6e74656e742d747970653a206170706c69636174696f6e2f6a736f6e0d0a757365722d6167656e743a20656c61737469637365617263682d70792f372e302e352028507974686f6e20332e372e37290d0a0d0a7b227175657279223a7b226d617463685f616c6c223a7b7d7d7d
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 504f5354202f64617461312f5f64656c6574655f62795f717565727920485454502f312e310d0a486f73743a206c6f63616c686f73743a393230300d0a4163636570742d456e636f64696e673a206964656e746974790d0a436f6e74656e742d4c656e6774683a2032360d0a636f6e6e656374696f6e3a206b6565702d616c6976650d0a636f6e74656e742d747970653a206170706c69636174696f6e2f6a736f6e0d0a757365722d6167656e743a20656c61737469637365617263682d70792f372e302e352028507974686f6e20332e372e37290d0a0d0a7b227175657279223a7b226d617463685f616c6c223a7b7d7d7d
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1206) ~[netty-handler-4.1.43.Final.jar:4.1.43.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274) ~[netty-handler-4.1.43.Final.jar:4.1.43.Final]

```

I am following the Open Distro Docker's Documentation to run this.

```docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:1.6.0```

On client side the error logs are:
```

ile "/home/gaurav/Projects/elasticsearch-dbapi/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 250, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))) caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))


```

The driver code could be triggered using the library's testing utility. 
I just run the ```tox``` utility.

I get the same error on this example as well [https://elasticsearch-py.readthedocs.io/en/master/#example-usage](url)

Error log:

```
python dummytest.py 
Object created!--------------
<class 'elasticsearch.client.Elasticsearch'>
Traceback (most recent call last):
  File "/home/gaurav/Projects/elasticsearch-dbapi/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/gaurav/Projects/elasticsearch-dbapi/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/gaurav/Projects/elasticsearch-dbapi/env/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

```

DummyTest.py

```
from datetime import datetime
from elasticsearch import Elasticsearch
es = Elasticsearch("http://localhost:9200" )
if es!=None:
 print("Object created!--------------")
else:
 print("Object Not created~~~~~~~~~~~~~")
print(type(es))
doc = {
    'author': 'kimchy',
    'text': 'Elasticsearch: cool. bonsai cool.',
    'timestamp': datetime.now(),
}
res = es.index(index="test-index", id=1, body=doc)
if es!=None:
 print("Object there!--------------")
else:
 print("Object Not there!~~~~~~~~~~~~~")
print(res['result'])

res = es.get(index="test-index", id=1)
print(res['_source'])

es.indices.refresh(index="test-index")

res = es.search(index="test-index", body={"query": {"match_all": {}}})
print("Got %d Hits:" % res['hits']['total']['value'])
for hit in res['hits']['hits']:
    print("%(timestamp)s %(author)s: %(text)s" % hit["_source"])

```

Hope,  this is the right place to submit this issue.

**Comment by gaurav1999** [comment]
Sorry, I need to use the disable security method. Will work on it.
