### ISSUE TITLE
Failed to parse query due to offending symbol [order]

### ISSUE THREAD

**Issue by yangjiajun2014** [opendistro-for-elasticsearch/sql#507]
I have a filed named order.Opendistro sql can't execute sqls when I use this filed.

For exampe:
select order from XXX
select * from XXX where order<> -1 

The error is：
[{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Failed to parse query due to offending symbol [order] at: 'select  ***,order' <--- HERE... More details: Expecting tokens in {'SELECT', '('}",
    "type": "SyntaxAnalysisException"
  },
  "status": 400
}]

How can I avoid this error

**Comment by abbashus** [comment]
@yangjiajun2014  Since `order` is a SQL keyword, it is interpreted differently by parser than identifier. To use identifiers same as SQL syntax keyword, you need to surround them with back-ticks.

This works:
```
# add doc
PUT test/_doc/1
{
  "order" : 10
}

# Request
POST  _opendistro/_sql/?
{ 
  "query" : "Select `order` FROM test "
}


#  Response
{
  "schema": [{
    "name": "order",
    "type": "long"
  }],
  "total": 1,
  "datarows": [[10]],
  "size": 1,
  "status": 200
}
```

**Comment by abbashus** [comment]
The other case `select * from XXX where order<> -1` is a bug. It works without back-ticks but fails with back-ticks.

```
# Add doc
PUT test_2/_doc/1
{
  "age" : 10
}
```

Works w/o back-ticks on identifier:
```
POST  _opendistro/_sql/?
{ "fetch_size" : 0,
  "query" : """
    SELECT * FROM test_2 WHERE age =  10
  """
}

# response
{
  "schema": [{
    "name": "age",
    "type": "long"
  }],
  "total": 1,
  "datarows": [[10]],
  "size": 1,
  "status": 200
}
```

Does not work with back-ticks
```

POST  _opendistro/_sql/?
{ 
  "query" : """
    SELECT * FROM test_2 WHERE `age` =  10
  """
}

# Response
{
  "error": {
    "reason": "Invalid SQL query",
    "details": "Operator [=] cannot work with [STRING, INTEGER]. Usage: Please use compatible types from each side.",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}

```

Error log:
```
[2020-06-04T21:01:13,452][INFO ][c.a.o.s.p.RestSqlAction  ] [f45c898a2ba7.ant.amazon.com] [5b025286-fa52-4f7d-8b56-445123a73918] Incoming request /_opendistro/_sql/?pretty=true: ( SELECT * FROM table WHERE identifier = number )
[2020-06-04T21:01:13,455][ERROR][c.a.o.s.p.RestSqlAction  ] [f45c898a2ba7.ant.amazon.com] 5b025286-fa52-4f7d-8b56-445123a73918 Client side error during query execution
com.amazon.opendistroforelasticsearch.sql.antlr.semantic.SemanticAnalysisException: Operator [=] cannot work with [STRING, INTEGER]. Usage: Please use compatible types from each side.
	at com.amazon.opendistroforelasticsearch.sql.antlr.semantic.types.Type.reduce(Type.java:57) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.reduce(AntlrSqlParseTreeVisitor.java:408) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitBinaryComparisonPredicate(AntlrSqlParseTreeVisitor.java:288) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitBinaryComparisonPredicate(AntlrSqlParseTreeVisitor.java:71) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$BinaryComparisonPredicateContext.accept(OpenDistroSqlParser.java:6366) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParserBaseVisitor.visitPredicateExpression(OpenDistroSqlParserBaseVisitor.java:566) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$PredicateExpressionContext.accept(OpenDistroSqlParser.java:6188) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitQuerySpecification(AntlrSqlParseTreeVisitor.java:160) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitQuerySpecification(AntlrSqlParseTreeVisitor.java:71) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$QuerySpecificationContext.accept(OpenDistroSqlParser.java:1945) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParserBaseVisitor.visitSimpleSelect(OpenDistroSqlParserBaseVisitor.java:41) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$SimpleSelectContext.accept(OpenDistroSqlParser.java:462) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParserBaseVisitor.visitDmlStatement(OpenDistroSqlParserBaseVisitor.java:34) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$DmlStatementContext.accept(OpenDistroSqlParser.java:363) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParserBaseVisitor.visitSqlStatement(OpenDistroSqlParserBaseVisitor.java:27) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$SqlStatementContext.accept(OpenDistroSqlParser.java:292) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46) ~[antlr4-runtime-4.7.1.jar:4.7.1]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParserBaseVisitor.visitRoot(OpenDistroSqlParserBaseVisitor.java:20) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitRoot(AntlrSqlParseTreeVisitor.java:83) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.visitor.AntlrSqlParseTreeVisitor.visitRoot(AntlrSqlParseTreeVisitor.java:71) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.parser.OpenDistroSqlParser$RootContext.accept(OpenDistroSqlParser.java:231) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.OpenDistroSqlAnalyzer.analyzeSemantic(OpenDistroSqlAnalyzer.java:89) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.antlr.OpenDistroSqlAnalyzer.analyze(OpenDistroSqlAnalyzer.java:59) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.performAnalysis(RestSqlAction.java:249) ~[opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.explainRequest(RestSqlAction.java:174) [opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at com.amazon.opendistroforelasticsearch.sql.plugin.RestSqlAction.prepareRequest(RestSqlAction.java:139) [opendistro_sql-1.8.0.0.jar:1.8.0.0]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:94) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:236) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:318) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:176) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:329) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:383) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:308) [elasticsearch-7.7.0.jar:7.7.0]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:54) [transport-netty4-client-7.7.0.jar:7.7.0]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:29) [transport-netty4-client-7.7.0.jar:7.7.0]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:58) [transport-netty4-client-7.7.0.jar:7.7.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) [netty-codec-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]

```

**Comment by anirudha** [comment]
please reopen if you need more information
