### ISSUE TITLE
Standalone integration test fails intermittently 

### ISSUE THREAD

**Issue by chloe-zh** [opendistro-for-elasticsearch/sql#559]
The standalone integration test `StandaloneIT` fails sometimes but typically it passes if given a retry. Need to investigate the root cause.

Log shows as follows
```
Suite: Test class com.amazon.opendistroforelasticsearch.sql.ppl.StandaloneIT
  1> [2020-07-09T19:25:04,426][INFO ][c.a.o.s.p.StandaloneIT   ] [testSourceFieldQuery] before test
  1> [2020-07-09T19:25:04,429][INFO ][c.a.o.s.p.StandaloneIT   ] [testSourceFieldQuery] initializing REST clients against [http://[::1]:60262, http://127.0.0.1:60263]
  1> [2020-07-09T19:25:08,752][INFO ][c.a.o.s.p.StandaloneIT   ] [testSourceFieldQuery] after test
  2> REPRODUCE WITH: ./gradlew ':integ-test:integTestRunner' --tests "com.amazon.opendistroforelasticsearch.sql.ppl.StandaloneIT.testSourceFieldQuery" -Dtests.seed=4F6A76B99F1B6E2C -Dtests.security.manager=false -Dtests.locale=tr -Dtests.timezone=America/Jamaica -Druntime.java=14
  2> org.junit.ComparisonFailure: expected:<...e",
        "type": "str[i]ng"
      }],
      "total":...> but was:<...e",
        "type": "str[ı]ng"
      }],
      "total":...>
        at __randomizedtesting.SeedInfo.seed([4F6A76B99F1B6E2C:D5E8FE3E9C18E222]:0)
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at com.amazon.opendistroforelasticsearch.sql.ppl.StandaloneIT.testSourceFieldQuery(StandaloneIT.java:89)
  2> NOTE: leaving temporary files on disk at: /Users/fizhang/workspace/opendistro/sql/integ-test/build/testrun/integTestRunner/temp/com.amazon.opendistroforelasticsearch.sql.ppl.StandaloneIT_4F6A76B99F1B6E2C-001
  2> NOTE: test params are: codec=Asserting(Lucene84): {}, docValues:{}, maxPointsInLeafNode=1807, maxMBSortInHeap=7.893458752461709, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@2deff505), locale=tr, timezone=America/Jamaica
  2> NOTE: Mac OS X 10.14.6 x86_64/Oracle Corporation 14.0.1 (64-bit)/cpus=4,threads=1,free=399194104,total=536870912
  2> NOTE: All tests run in this JVM: [RenameCommandIT, FieldsCommandIT, StatsCommandIT, WhereCommandIT, SortCommandIT, ResourceMonitorIT, OperatorIT, SearchCommandIT, StandaloneIT]

```

**Comment by dai-chen** [comment]
Didn't see this happen again. Closing and will reopen as needed.
