### ISSUE TITLE
bug in JSON Support 

### ISSUE THREAD

**Issue by Hokwang** [opendistro-for-elasticsearch/sql#607]
Hello.

I am reading and following your document, as beginner.

In `JSON Support` page (https://opendistro.github.io/for-elasticsearch-docs/docs/sql/partiql/),

When I follow below query,
```
SELECT e.name AS employeeName,
       p.name AS projectName
FROM employees_nested AS e,
       e.projects AS p
WHERE p.name LIKE '%security%'
```
Messages said `Employees_nested: no response`.

Please check.

**Comment by dai-chen** [comment]
@Hokwang , thanks for reporting the issue! From the error message, I assume you were using our SQL Workbench UI. I wonder did you index the test data in our doc to your Elasticsearch cluster?

**Comment by Hokwang** [comment]
@dai-chen absolutely.

```
GET employees_nested/_search
{
  "query": {
    "match_all": {}
  }
}
```
result is
```
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "employees_nested",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "id" : 3,
          "name" : "Bob Smith",
          "title" : null,
          "projects" : [
            {
              "name" : "SQL Spectrum querying",
              "started_year" : 1990
            },
            {
              "name" : "SQL security",
              "started_year" : 1999
            },
            {
              "name" : "Elasticsearch security",
              "started_year" : 2015
            }
          ]
        }
      },
      {
        "_index" : "employees_nested",
        "_type" : "_doc",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "id" : 4,
          "name" : "Susan Smith",
          "title" : "Dev Mgr",
          "projects" : [ ]
        }
      },
      {
        "_index" : "employees_nested",
        "_type" : "_doc",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "id" : 6,
          "name" : "Jane Smith",
          "title" : "Software Eng 2",
          "projects" : [
            {
              "name" : "SQL security",
              "started_year" : 1998
            },
            {
              "name" : "Hello security",
              "started_year" : 2015,
              "address" : [
                {
                  "city" : "Dallas",
                  "state" : "TX"
                }
              ]
            }
          ]
        }
      }
    ]
  }
}
```

**Comment by dai-chen** [comment]
@Hokwang Thanks for the info! Will try to reproduce.

**Comment by Hokwang** [comment]
@dai-chen any updates?

**Comment by chloe-zh** [comment]
Hi @Hokwang I've tried to reproduce the issue but the query works well and has consistent behavior with what's in the documentation. Could you have a try in the command line or in the devtools to check the error log?

**Comment by Hokwang** [comment]
@chloe-zh 
Thanks for your reply.

I am re-trying at workbench,
here's log.

```
{"type":"response","@timestamp":"2020-07-31T02:07:35Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/31997/bundles/af7ae505a9eed503f8b8e6982036873e.woff2","method":"get","headers":{"host":"company.net","x-request-id":"86cb3f365787035168e4fa6ad1c00063","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1","x-forwarded-host":"company.net","x-forwarded-port":"443","x-forwarded-proto":"https","x-scheme":"https","origin":"https://company.net","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","dnt":"1","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"font","referer":"https://company.net/kibana-stage/31997/bundles/commons.style.css","accept-encoding":"gzip, deflate, br","accept-language":"ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"__user__"},"remoteAddress":"10.244.12.113","userAgent":"10.244.12.113","referer":"https://company.net/kibana-stage/31997/bundles/commons.style.css"},"res":{"statusCode":200,"responseTime":4,"contentLength":9},"message":"GET /31997/bundles/af7ae505a9eed503f8b8e6982036873e.woff2 200 4ms - 9.0B"}
{ Error: Bad Request
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 400,
  displayName: 'BadRequest',
  message: 'Bad Request',
  path: '/_opendistro/_sql',
  query: {},
  body:
   '{\n  "error": {\n    "reason": "Invalid SQL query",\n    "details": "Operator [JOIN] cannot work with [INDEX, OBJECT]. Usage: Please join index with other index or its nested field.",\n    "type": "SemanticAnalysisException"\n  },\n  "status": 400\n}',
  statusCode: 400,
  response:
   '{\n  "error": {\n    "reason": "Invalid SQL query",\n    "details": "Operator [JOIN] cannot work with [INDEX, OBJECT]. Usage: Please join index with other index or its nested field.",\n    "type": "SemanticAnalysisException"\n  },\n  "status": 400\n}',
  toString: [Function],
  toJSON: [Function] }
{"type":"response","@timestamp":"2020-07-31T02:07:51Z","tags":[],"pid":1,"method":"post","statusCode":200,"req":{"url":"/api/sql_console/translate","method":"post","headers":{"host":"company.net","x-request-id":"5243255844d5de3fe02dd6cab316b8b2","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1","x-forwarded-host":"company.net","x-forwarded-port":"443","x-forwarded-proto":"https","x-scheme":"https","content-length":"165","accept":"application/json, text/plain, */*","dnt":"1","kbn-version":"7.8.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","content-type":"application/json;charset=UTF-8","origin":"https://company.net","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://company.net/kibana-stage/app/opendistro-sql-workbench","accept-encoding":"gzip, deflate, br","accept-language":"ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"__user__"},"remoteAddress":"10.244.3.75","userAgent":"10.244.3.75","referer":"https://company.net/kibana-stage/app/opendistro-sql-workbench"},"res":{"statusCode":200,"responseTime":23,"contentLength":9},"message":"POST /api/sql_console/translate 200 23ms - 9.0B"}
Debug: internal, implementation, error 
    TypeError: Cannot read property 'message' of undefined
    at _callee$ (/usr/share/kibana/plugins/opendistro-sql-workbench/server/services/QueryService.js:99:27)
    at tryCatch (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/usr/share/kibana/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (/usr/share/kibana/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
{"type":"error","@timestamp":"2020-07-31T02:07:51Z","tags":[],"pid":1,"level":"error","error":{"message":"Cannot read property 'message' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'message' of undefined\n    at _callee$ (/usr/share/kibana/plugins/opendistro-sql-workbench/server/services/QueryService.js:99:27)\n    at tryCatch (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)\n    at Generator.invoke [as _invoke] (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)\n    at Generator.prototype.(anonymous function) [as throw] (/usr/share/kibana/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)\n    at asyncGeneratorStep (/usr/share/kibana/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _throw (/usr/share/kibana/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/api/sql_console/query","path":"/api/sql_console/query","href":"/api/sql_console/query"},"message":"Cannot read property 'message' of undefined"}
{"type":"response","@timestamp":"2020-07-31T02:07:51Z","tags":[],"pid":1,"method":"post","statusCode":500,"req":{"url":"/api/sql_console/query","method":"post","headers":{"host":"company.net","x-request-id":"e791f0f384f5257899a80ff0e4754b42","x-real-ip":"127.0.0.1","x-forwarded-for":"127.0.0.1","x-forwarded-host":"company.net","x-forwarded-port":"443","x-forwarded-proto":"https","x-scheme":"https","content-length":"165","accept":"application/json, text/plain, */*","dnt":"1","kbn-version":"7.8.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","content-type":"application/json;charset=UTF-8","origin":"https://company.net","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","sec-fetch-dest":"empty","referer":"https://company.net/kibana-stage/app/opendistro-sql-workbench","accept-encoding":"gzip, deflate, br","accept-language":"ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7","securitytenant":"__user__"},"remoteAddress":"10.244.3.75","userAgent":"10.244.3.75","referer":"https://company.net/kibana-stage/app/opendistro-sql-workbench"},"res":{"statusCode":500,"responseTime":24,"contentLength":9},"message":"POST /api/sql_console/query 500 24ms - 9.0B"}
```

**Comment by Hokwang** [comment]
I install odfe-sql-cli,
```
# pip install odfe-sql-cli
Collecting odfe-sql-cli
  Using cached odfe_sql_cli-1.9.0.0-py3-none-any.whl (24 kB)
Collecting elasticsearch==7.5.1
  Using cached elasticsearch-7.5.1-py2.py3-none-any.whl (86 kB)
Requirement already satisfied: requests-aws4auth==0.9 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (0.9)
Requirement already satisfied: boto3==1.9.181 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (1.9.181)
Requirement already satisfied: cli-helpers[styles]==1.2.1 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (1.2.1)
Requirement already satisfied: Pygments==2.6.1 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (2.6.1)
Requirement already satisfied: click==7.1.1 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (7.1.1)
Requirement already satisfied: prompt-toolkit==2.0.6 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (2.0.6)
Requirement already satisfied: pyfiglet==0.8.post1 in /usr/local/lib/python3.7/site-packages (from odfe-sql-cli) (0.8.post1)
Requirement already satisfied: urllib3>=1.21.1 in /usr/local/lib/python3.7/site-packages (from elasticsearch==7.5.1->odfe-sql-cli) (1.25.9)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from requests-aws4auth==0.9->odfe-sql-cli) (2.24.0)
Requirement already satisfied: botocore<1.13.0,>=1.12.181 in /usr/local/lib/python3.7/site-packages (from boto3==1.9.181->odfe-sql-cli) (1.12.253)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.7/site-packages (from boto3==1.9.181->odfe-sql-cli) (0.10.0)
Requirement already satisfied: s3transfer<0.3.0,>=0.2.0 in /usr/local/lib/python3.7/site-packages (from boto3==1.9.181->odfe-sql-cli) (0.2.1)
Requirement already satisfied: terminaltables>=3.0.0 in /usr/local/lib/python3.7/site-packages (from cli-helpers[styles]==1.2.1->odfe-sql-cli) (3.1.0)
Requirement already satisfied: configobj>=5.0.5 in /usr/local/lib/python3.7/site-packages (from cli-helpers[styles]==1.2.1->odfe-sql-cli) (5.0.6)
Requirement already satisfied: tabulate[widechars]>=0.8.2 in /usr/local/lib/python3.7/site-packages (from cli-helpers[styles]==1.2.1->odfe-sql-cli) (0.8.7)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from prompt-toolkit==2.0.6->odfe-sql-cli) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt-toolkit==2.0.6->odfe-sql-cli) (0.2.5)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->requests-aws4auth==0.9->odfe-sql-cli) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->requests-aws4auth==0.9->odfe-sql-cli) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->requests-aws4auth==0.9->odfe-sql-cli) (2.10)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/local/lib/python3.7/site-packages (from botocore<1.13.0,>=1.12.181->boto3==1.9.181->odfe-sql-cli) (0.15.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python3.7/site-packages (from botocore<1.13.0,>=1.12.181->boto3==1.9.181->odfe-sql-cli) (2.8.1)
Installing collected packages: elasticsearch, odfe-sql-cli
  Attempting uninstall: elasticsearch
    Found existing installation: elasticsearch 7.8.1
    Uninstalling elasticsearch-7.8.1:
      Successfully uninstalled elasticsearch-7.8.1
Successfully installed elasticsearch-7.5.1 odfe-sql-cli-1.9.0.0
```

This module using 7.5.1, uninstalled 7.8.1 but your elastic version is 7.8 in odfe 1.9.0.

**Comment by Hokwang** [comment]
and cli is same,

```
odfesql> SELECT e.name AS employeeName, 
........        p.name AS projectName 
........ FROM employees_nested AS e, 
........        e.projects AS p 
........ WHERE p.name LIKE '%security%' ;
{'reason': 'Invalid SQL query', 'details': 'Operator [JOIN] cannot work with [INDEX, OBJECT]. Usage: Please join index with other index or its nested field.', 'type': 'SemanticAnalysisException'}
odfesql> SELECT e.name AS employeeName FROM employees_nested AS e;                                                                                                                                 
fetched rows / total rows = 3/3
+-------------+
| name        |
|-------------|
| Bob Smith   |
| Susan Smith |
| Jane Smith  |
+-------------+
odfesql> SELECT p.name AS projectName FROM employees_nested AS e, e.projects AS p;                                                                                                                 
{'reason': 'Invalid SQL query', 'details': 'Operator [JOIN] cannot work with [INDEX, OBJECT]. Usage: Please join index with other index or its nested field.', 'type': 'SemanticAnalysisException'}
odfesql> SELECT e.projects.name AS projectName FROM employees_nested AS e;                                                                                                                         
fetched rows / total rows = 3/3
+-----------------+
| projects.name   |
|-----------------|
| null            |
| null            |
| null            |
+-----------------+
odfesql> SELECT e.projects.* AS projectName FROM employees_nested AS e;                                                                                                                            
{'reason': 'Invalid SQL query', 'details': "Failed to parse query due to offending symbol [AS] at: 'SELECT e.projects.* AS' <--- HERE... More details: Expecting tokens in {'SELECT', '('}", 'type': 'SyntaxAnalysisException'}
odfesql> SELECT e.projects FROM employees_nested AS e;                                                                                                                                             
fetched rows / total rows = 3/3
```

**Comment by chloe-zh** [comment]
It looks like the mapping of the nested fields is incorrect. Could you try to create the index after setting the following mapping:
```
PUT employees_nested/_mapping
{
  "properties":{
    "id":{
      "type":"long"
    },
    "name":{
      "type":"text",
      "fields":{
        "keyword":{
          "type":"keyword",
          "ignore_above":256
        }
      }
    },
    "projects":{
      "type":"nested",
      "properties":{
        "name":{
          "type":"text",
          "fields":{
            "keyword":{
              "type":"keyword"
            }
          },
          "fielddata":true
        },
        "started_year":{
          "type":"long"
        }
      }
    },
    "title":{
      "type":"text",
      "fields":{
        "keyword":{
          "type":"keyword",
          "ignore_above":256
        }
      }
    }
  }
}
```

**Comment by Hokwang** [comment]
@chloe-zh 
When I `DELETE employees_nested` and then re-create 
```
POST employees_nested/_bulk?refresh
{"index":{"_id":"1"}}
{"id":3,"name":"Bob Smith","title":null,"projects":[{"name":"SQL Spectrum querying","started_year":1990},{"name":"SQL security","started_year":1999},{"name":"Elasticsearch security","started_year":2015}]}
{"index":{"_id":"2"}}
{"id":4,"name":"Susan Smith","title":"Dev Mgr","projects":[]}
{"index":{"_id":"3"}}
{"id":6,"name":"Jane Smith","title":"Software Eng 2","projects":[{"name":"SQL security","started_year":1998},{"name":"Hello security","started_year":2015,"address":[{"city":"Dallas","state":"TX"}]}]}
```
and check mapping (create automatically)
```
{
  "employees_nested" : {
    "aliases" : { },
    "mappings" : {
      "properties" : {
        "id" : {
          "type" : "long"
        },
        "name" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "projects" : {
          "properties" : {
            "address" : {
              "properties" : {
                "city" : {
                  "type" : "text",
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                },
                "state" : {
                  "type" : "text",
                  "fields" : {
                    "keyword" : {
                      "type" : "keyword",
                      "ignore_above" : 256
                    }
                  }
                }
              }
            },
            "name" : {
              "type" : "text",
              "fields" : {
                "keyword" : {
                  "type" : "keyword",
                  "ignore_above" : 256
                }
              }
            },
            "started_year" : {
              "type" : "long"
            }
          }
        },
        "title" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1596435694914",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "HeFxJvuCQL2fp_xlRx6CsA",
        "version" : {
          "created" : "7080099"
        },
        "provided_name" : "employees_nested"
      }
    }
  }
}
```
I remove index, re-create index and create mapping as you mentioned, and bulk input, SQL workbench works!

I think `projects: { "type": "nested" }` is important thing.

is there a options for creating `nested` type automatically ? ( I am beginner of elastic. )
And still does this issue occurs only for me? or do you need to mention this mapping at your document ?

**Comment by Hokwang** [comment]
@chloe-zh 

if there's no problem with this, you can close this case.

**Comment by dai-chen** [comment]
> @chloe-zh
> 
> if there's no problem with this, you can close this case.

Yes, `nested` is important which makes the field different from default `object` type. You need to specify it in index mapping or index template. Thanks for reporting this. I've noted it and will clarify this: https://github.com/opendistro-for-elasticsearch/sql/issues/528
