### ISSUE TITLE
NPE when use where on left join scenario

### ISSUE THREAD

**Issue by seraphjiang** [opendistro-for-elasticsearch/sql#657]
This was on 1.4.0.0, elasticsearch 7.4.2

below query got NPE
```
 select t1.domainIdentity AS domainIdentity,  from issue* as t1 left join config as dc
 on 
 t1.id.keyword = dc.id.keyword
  WHERE 
  tms.issueType like '%backend%'  AND snapshotAt < '2020-08-03T19:10:00Z' AND snapshotAt >= '2020-08-03T19:00:00Z' AND resolved='0'

```

query works if only keep first where condition
```
 select t1.domainIdentity AS domainIdentity,  from issue* as t1 left join config as dc
 on 
 t1.id.keyword = dc.id.keyword
  WHERE 
  tms.issueType like '%backend%' 

```

Is it a known issue for sql on 1.4.0.0?

**Comment by dai-chen** [comment]
When I changed the index pattern to a specific index, the issue goes away. The exception was thrown from our term rewriter which rewrites text to text.keyword. There seems problem with getting index mapping for index pattern.

```
java.lang.NullPointerException: null
       at com.amazon.opendistroforelasticsearch.sql.rewriter.matchtoterm.TermFieldRewriter.visit(TermFieldRewriter.java:140) ~[opendistro_sql-1.4.0.0.jar:1.4.0.0]
       at com.alibaba.druid.sql.ast.expr.SQLIdentifierExpr.accept0(SQLIdentifierExpr.java:65) ~[druid-1.0.15.jar:1.0.15]
       at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40) ~[druid-1.0.15.jar:1.0.15]
       at com.alibaba.druid.sql.ast.SQLObjectImpl.acceptChild(SQLObjectImpl.java:62) ~[druid-1.0.15.jar:1.0.15]
```

**Comment by spijet** [comment]
In my case I get an NPE as soon as I add any `WHERE` condition referring to the second index. The query looks like this:
```sql
SELECT *
FROM index.one-2021.11.* AS a
LEFT JOIN index.two-2021.11.* AS b
ON a.some_field.keyword = b.some_field.keyword
WHERE b.other_field = 1234 AND b.third_field = 5678;
```

The query works if I remove the `WHERE` clause or change the wildcards to full index names.

**Comment by evanhalley** [comment]
I see similar behavior, except I'm querying (and JOINing) two aliased indices.

```
SELECT a.id AS aId,
  a.status AS aStatus,
  a.obj.1234.progress AS progress,
  a.obj.5678.dateModified AS dateAssigned,
  t.id AS tId
FROM aliased-index-a a
LEFT JOIN aliased-index-t t ON a.id = t.a_id
WHERE a.id <> null
  AND a.otherStatus = 'someStatus'
  AND a.otherFilter <> 'example'
  AND t.anId = '093734'
  AND t.taskStatus = 'abcdef';
```

The above query returns:

```
{
	"error": {
		"reason": "Invalid SQL query",
		"details": "",
		"type": "NullPointerException"
	},
	"status": 400
}
```

Removing a WHERE clause or querying the underlying index directly resolves the issue (and returns data). Is there a fix or workaround where I can continue to query the aliased indices in this scenario?

**Comment by diggerbonk** [comment]
I am seeing the same thing. OpenSearch 1.3.2.

* When using an IN subquery, where the subquery references an index alias
* When using a join with a where clause that references an index alias
