### ISSUE TITLE
[New engine] Error occurred when unsupported data type present in index

### ISSUE THREAD

**Issue by dai-chen** [opendistro-for-elasticsearch/sql#683]
Because `SELECT` expression is not pushed down in new engine yet, any field of unsupported type, ex. `half_float`, `geo_point`, will cause exception when IndexScan operator fetches all fields and convert to ExprValue for each document.

```
[2020-08-13T14:29:07,174][INFO ][c.a.o.s.l.p.RestSqlAction] [186590df9563.ant.amazon.com] [c184a718-7952-411e-9eaf-60588b15ce05] Request SQLQueryRequest(jsonContent={"query":"SELECT customer_full_name FROM kibana_sample_data_ecommerce WHERE customer_full_name LIKE 'B%'"}, query=SELECT customer_full_name FROM kibana_sample_data_ecommerce WHERE customer_full_name LIKE 'B%', path=/_opendistro/_sql, format=jdbc) is handled by new SQL query engine
[2020-08-13T14:29:07,377][ERROR][c.a.o.s.l.p.RestSQLQueryAction] [186590df9563.ant.amazon.com] Error happened during query handling
java.lang.IllegalStateException: Unsupported type: UNKNOWN for field: taxful_total_price, value: 53.98.
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.data.value.ElasticsearchExprValueFactory.construct(ElasticsearchExprValueFactory.java:125) ~[elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.data.value.ElasticsearchExprValueFactory.lambda$constructStruct$0(ElasticsearchExprValueFactory.java:238) ~[elasticsearch-1.9.0.1.jar:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.data.value.ElasticsearchExprValueFactory.constructStruct(ElasticsearchExprValueFactory.java:237) ~[elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.data.value.ElasticsearchExprValueFactory.construct(ElasticsearchExprValueFactory.java:84) ~[elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.storage.ElasticsearchIndexScan.next(ElasticsearchIndexScan.java:89) ~[elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.storage.ElasticsearchIndexScan.next(ElasticsearchIndexScan.java:41) ~[elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.planner.physical.ProjectOperator.next(ProjectOperator.java:61) ~[core-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.planner.physical.ProjectOperator.next(ProjectOperator.java:35) ~[core-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.executor.ElasticsearchExecutionEngine.lambda$execute$0(ElasticsearchExecutionEngine.java:47) [elasticsearch-1.9.0.1.jar:?]
	at com.amazon.opendistroforelasticsearch.sql.elasticsearch.client.ElasticsearchNodeClient.lambda$withCurrentContext$2(ElasticsearchNodeClient.java:148) [elasticsearch-1.9.0.1.jar:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:636) [elasticsearch-7.8.0.jar:7.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by dai-chen** [comment]
Fixed in https://github.com/opendistro-for-elasticsearch/sql/pull/719/files
