### ISSUE TITLE
Using index pattern in FROM fails

### ISSUE THREAD

**Issue by Ricaz** [opendistro-for-elasticsearch/sql#708]
Hi. I'm trying to use the SQL feature to export data, since that seems to be the only way.

I can do queries directly on specific indices:
```js
POST _opendistro/_sql
{
  "query": "SELECT message FROM sysip-000121"
}
```
And it returns a proper result.
When I use and index pattern instead:
```js
POST _opendistro/_sql
{
  "query": "SELECT message FROM sysip-*"
}
```
I get an error:
```json
{
  "error": {
    "reason": "There was internal problem at backend",
    "details": "",
    "type": "NoSuchElementException"
  },
  "status": 500
}
```

In my cluster's logs, I get an exception like this:
```
[2020-08-25T13:49:32,643][INFO ][c.a.o.s.p.RestSqlAction  ] [REDACTED][890e27fb-f867-480f-8fcc-c2d93f8be55b] Incoming request /_opendistro/_sql?pretty=true: ( SELECT message FROM table )
[2020-08-25T13:49:32,703][WARN ][c.a.o.s.e.f.PrettyFormatRestExecutor] [REDACTED]Error happened in pretty formatter
java.util.NoSuchElementException: null
        at com.google.common.collect.Iterators$1.next(Iterators.java:80) ~[guava-15.0.jar:?]
        at com.amazon.opendistroforelasticsearch.sql.esdomain.mapping.Mappings.firstMapping(Mappings.java:46) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatter.getDateFieldFormatMap(DateFieldFormatter.java:128) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.DateFieldFormatter.<init>(DateFieldFormatter.java:57) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.SelectResultSet.<init>(SelectResultSet.java:120) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.loadResultSet(Protocol.java:104) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.Protocol.<init>(Protocol.java:74) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.buildProtocolForDefaultQuery(PrettyFormatRestExecutor.java:113) ~[opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:77) [opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.format.PrettyFormatRestExecutor.execute(PrettyFormatRestExecutor.java:53) [opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.doExecuteWithTimeMeasured(AsyncRestExecutor.java:161) [opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.executor.AsyncRestExecutor.lambda$async$1(AsyncRestExecutor.java:121) [opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at com.amazon.opendistroforelasticsearch.sql.utils.LogUtils.lambda$withCurrentContext$0(LogUtils.java:72) [opendistro_sql-1.9.0.0.jar:1.9.0.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:636) [elasticsearch-7.8.0.jar:7.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

Note: I turned off `opendistro.sql.query.analysis.enabled`.

I also tried with `?pretty=false`.
I am 100% sure that is the name of the index pattern.

Not sure how to debug this. Can you please help me?
I really need this to work as it is quite cumbersome to have to first figure out which indices the documents you are looking for are in.

**Comment by dai-chen** [comment]
@Ricaz Thanks for reporting the issue! From the error stack you posted, it seems some error when formatting date field. Could you please share your index mapping? And one or a few more test documents can also help. Thanks!

**Comment by dai-chen** [comment]
Closing due to insufficient info to investigate. Feel free to reopen. Thanks!
