### ISSUE TITLE
Build fails when locale is set to other than English

### ISSUE THREAD

**Issue by pakio** [opendistro-for-elasticsearch/sql#824]
### Description
Trying to set up this plugin for my local Elasticsearch with referene to readme,  `./gradlew build` fails on unit test.

#### Detail
2 Tests fails because of the locale time set to my laptop.
* DateTimeFunctionTest.dayName()
* DateTimeFunctionTest.monthName()

with showing these messages.
<img width="1350" alt="screen shot" src="https://user-images.githubusercontent.com/11995398/99147575-7ba8b980-26c5-11eb-8fac-c5987af2bc1e.png">

```
org.opentest4j.AssertionFailedError: expected: <"Friday"> but was: <"金曜日">
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at com.amazon.opendistroforelasticsearch.sql.expression.datetime.DateTimeFunctionTest.dayName(DateTimeFunctionTest.java:393)
...
```

After setting my locale to en_US these errors were disappeared so it's ok for now.

#### branch 
* master

#### environment
```
Gradle version : 6.5
Java Version : openjdk 14.0.1
locale : ja_JP
```

**Comment by chloe-zh** [comment]
Thank you for reporting this issue! Will investigate and optimize it.

**Comment by pakio** [comment]
Thank you for taking time! If I can help in any way, I'd be happy to contribute
