### ISSUE TITLE
JDBC incompatible with Apache Spark and nested fields

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/sql#897]
This is some kind of cross framework issue between Opendistro and [Apache Spark](http://spark.apache.org/) and nested field support, which is not working.

I'm creating the issue in Opendistro, because I guess, the root cause relies in Opendistro SQL, as Sparks nested field support is orthogonal to Data Sources in Spark and it's working well for other kind of data sources. But please correct me if thats a wrong assumption.

Having two simple indexes in Opendistro:
```
POST foo1/_doc
{"foo1": { "bar": "value" } }

POST foo2/_doc
{"foo1": { "bar1": "value" }, "foo2": { "bar2": "value" } }
```

Reading documents from `foo1` / `foo2` indexes through Apache Spark SQL [JDBC Integration](https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html) via Opendistro JDBC Driver results in unexpected behavior or errors:

#### First lets start an interactive pyspark Session with Opendistro JDBC...
```
# download and unpack and change dir
wget https://downloads.apache.org/spark/spark-3.0.1/spark-3.0.1-bin-hadoop2.7.tgz; tar xzf spark-3.0.1-bin-hadoop2.7.tgz; cd spark-3.0.1-bin-hadoop2.7

# start off pyspark with opendistro-sql-jdbc package
PYSPARK_PYTHON=python3 bin/pyspark --packages com.amazon.opendistroforelasticsearch.client:opendistro-sql-jdbc:1.11.0.0
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
20/12/07 15:34:37 WARN Utils: Your hostname, aws-wsg8-ug resolves to a loopback address: 127.0.1.1; using 172.16.56.135 instead (on interface eno1)
20/12/07 15:34:37 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/jars/spark-unsafe_2.12-3.0.1.jar) to constructor java.nio.DirectByteBuffer(lon
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Ivy Default Cache set to: /home/andreas/.ivy2/cache
The jars for the packages stored in: /home/andreas/.ivy2/jars
:: loading settings :: url = jar:file:/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
com.amazon.opendistroforelasticsearch.client#opendistro-sql-jdbc added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-3d881ba1-5e59-4beb-a76b-46d95ccc6319;1.0
        confs: [default]
        found com.amazon.opendistroforelasticsearch.client#opendistro-sql-jdbc;1.11.0.0 in central
:: resolution report :: resolve 124ms :: artifacts dl 2ms
        :: modules in use:
        com.amazon.opendistroforelasticsearch.client#opendistro-sql-jdbc;1.11.0.0 from central in [default]
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
        ---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-3d881ba1-5e59-4beb-a76b-46d95ccc6319
        confs: [default]
        0 artifacts copied, 1 already retrieved (0kB/3ms)
20/12/07 15:34:37 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 3.0.1
      /_/

Using Python version 3.6.9 (default, Oct  8 2020 12:12:24)
SparkSession available as 'spark'.
>>>
```

#### Now first trying to read `foo1` via sparks `dbtable` variable gives:

```
>>> df = (spark.read.format("jdbc")
    .option("driver", "com.amazon.opendistroforelasticsearch.jdbc.Driver")
    .option("url", "jdbc:elasticsearch://https://localhost:9200?trustSelfSigned=true&hostnameVerification=false")
    .option("dbtable", "foo1")
    .option("user", "admin")
    .option("password", "admin")
).load().printSchema()

Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 128, in deco
    return f(*a, **kw)
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o84.load.
: java.sql.SQLException: Error executing query
        at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:86)
        at com.amazon.opendistroforelasticsearch.jdbc.PreparedStatementImpl.executeQueryX(PreparedStatementImpl.java:87)
        at com.amazon.opendistroforelasticsearch.jdbc.PreparedStatementImpl.executeQuery(PreparedStatementImpl.java:78)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:61)
        at org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation$.getSchema(JDBCRelation.scala:226)
        at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:35)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:344)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:297)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:286)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:286)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:221)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.amazon.opendistroforelasticsearch.jdbc.protocol.http.HttpException: HTTP Code: 400. Message: Bad Request. Raw response received: {
  "error": {
    "reason": "Invalid SQL query",
    "details": "Field [foo1] have conflict type [[INDEX [foo1], ES Data Type [OBJECT]]]",
    "type": "SemanticAnalysisException"
  },
  "status": 400
}
        at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.checkResponseForErrors(JsonHttpResponseHandler.java:83)
        at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.handleResponse(JsonHttpResponseHandler.java:52)
        at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpResponseHandler.handleResponse(JsonHttpResponseHandler.java:45)
        at com.amazon.opendistroforelasticsearch.jdbc.protocol.http.JsonHttpProtocol.execute(JsonHttpProtocol.java:97)
        at com.amazon.opendistroforelasticsearch.jdbc.StatementImpl.executeQueryRequest(StatementImpl.java:74)
        ... 22 more

```

#### Next trying to read `foo1` via sparks `query` variable gives no error, but doesn't read schema properly (fieldname seems empty)
```
>>> df = (spark.read.format("jdbc")
    .option("driver", "com.amazon.opendistroforelasticsearch.jdbc.Driver")
    .option("url", "jdbc:elasticsearch://https://localhost:9200?https://github.com/opendistro-for-elasticsearch/sql/issues/897trustSelfSigned=true&hostnameVerification=false")
    .option("query", "select * from foo1")
    .option("user", "admin")
    .option("password", "admin")
).load().printSchema()

root
 |-- : string (nullable = true)
```

Spark end user would expect the correct schema like
```
root
 |-- foo: struct (nullable = true)
 |    |-- bar: string (nullable = true)
```

#### Next trying to read `foo2` results in another error again, this time two empty field names result in `Found duplicate column(s) in the data schema: ```
```
>>> df = (spark.read.format("jdbc")
    .option("driver", "com.amazon.opendistroforelasticsearch.jdbc.Driver")
    .option("url", "jdbc:elasticsearch://https://localhost:9200?trustSelfSigned=true&hostnameVerification=false")
    .option("query", "select * from foo2")
    .option("user", "admin")
    .option("password", "admin")
).load().printSchema()

Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/home/andreas/Downloads/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Found duplicate column(s) in the data schema: ``;
```

I would expect something like
```
root
 |-- foo1: struct (nullable = true)
 |    |-- bar: string (nullable = true)
 |-- foo2: struct (nullable = true)
 |    |-- bar: string (nullable = true)
```

**Comment by dai-chen** [comment]
@weand Thanks for reporting the issue. Will investigate.

**Comment by dai-chen** [comment]
@weand Thanks for the detailed info! I'm able to reproduce the issue for index `foo2` and not for index `foo1`.

I double checked both SELECT and DESCRIBE query result of our SQL plugin which looked right to me. However, spark kept complaining "Found duplicate column(s) in the data schema: ``" even though I changed your field name.

```
POST foo2/_doc
{"foobar": { "foo": "value" }, "barfoo": { "bar": "value" } }

>>> df = (spark.read.format("jdbc")
...     .option("driver", "com.amazon.opendistroforelasticsearch.jdbc.Driver")
...     .option("url", "jdbc:elasticsearch://http://localhost:9200")
...     .option("query", "select * from foo2")
... ).load().printSchema()
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Found duplicate column(s) in the data schema: ``;
>>>
>>>
>>> df = (spark.read.format("jdbc")
...     .option("driver", "com.amazon.opendistroforelasticsearch.jdbc.Driver")
...     .option("url", "jdbc:elasticsearch://http://localhost:9200")
...     .option("dbtable", "foo2")
... ).load().printSchema()
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/readwriter.py", line 184, in load
    return self._df(self._jreader.load())
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
  File "/Users/daichen/Temp/spark-3.0.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 134, in deco
    raise_from(converted)
  File "<string>", line 3, in raise_from
pyspark.sql.utils.AnalysisException: Found duplicate column(s) in the data schema: ``;
```

I don't have much experience in this and not sure how it uses our JDBC driver. Probably you need to check its doc. Let me know if you found anything error in our plugin. Thanks!

**Comment by dai-chen** [comment]
Closing. Feel free to reopen if anything else. Thanks!
